### ISSUE TITLE
Bands of CELC 2023 Not Centered

### ISSUE THREAD

**Issue by Risath18** [CELC2023/website#11]
![image](https://user-images.githubusercontent.com/66147598/163301756-e7346330-eeff-4b07-8a4a-27c73462893a.png)

Not aligned properly. Also, the Canada map needs to move left more.

**Comment by PixelPoncho** [comment]
Do you mean to have `The Bands of Celc 2023` left-aligned so it matches the `What is CELC?` text? @Risath18

**Comment by Risath18** [comment]
yes
